/**
 * Static evidence only. This registry is architecture metadata and MUST NOT be
 * imported by application runtime code.
 */
export const PROPOSED_DECISIONS = [
  "retain", "merge-after-parity", "hide-from-standard-navigation", "deprecate",
  "redirect", "remove-after-evidence", "protected-do-not-touch",
] as const;
export const CONFIDENCE_LEVELS = ["low", "medium", "high", "verified"] as const;

export type EvidenceReference = { file: string; line: number; detail: string };
export type DeprecationCandidate = {
  id: string;
  kind: "file" | "route" | "api" | "component" | "component-family";
  path: string;
  repositoryPaths: readonly string[];
  historicalPaths: readonly string[];
  repositoryState: "active" | "removed";
  category: string;
  currentStatus: string;
  proposedDecision: (typeof PROPOSED_DECISIONS)[number];
  confidence: (typeof CONFIDENCE_LEVELS)[number];
  risk: "low" | "medium" | "high" | "critical";
  owner: string;
  directReferences: readonly EvidenceReference[];
  indirectReferences: readonly EvidenceReference[];
  navigationReferences: readonly EvidenceReference[];
  documentationReferences: readonly EvidenceReference[];
  scriptReferences: readonly EvidenceReference[];
  apiDependencies: readonly string[];
  dataDependencies: readonly string[];
  hardwareDependencies: readonly string[];
  externalLinkRisk: string;
  tokenCompatibilityRisk: string;
  runtimeEvidence: readonly EvidenceReference[];
  evidenceGaps: readonly string[];
  prerequisites: readonly string[];
  observationPeriod: string;
  rollbackPlan: string;
  notes: string;
};

const ref = (file: string, line: number, detail: string): EvidenceReference => ({ file, line, detail });
const candidate = (entry: Partial<DeprecationCandidate> & Pick<DeprecationCandidate, "id" | "kind" | "path" | "repositoryPaths" | "category" | "currentStatus" | "proposedDecision" | "confidence" | "risk" | "owner" | "rollbackPlan" | "notes">): DeprecationCandidate => ({
  historicalPaths: [], repositoryState: "active",
  directReferences: [], indirectReferences: [], navigationReferences: [], documentationReferences: [], scriptReferences: [],
  apiDependencies: [], dataDependencies: [], hardwareDependencies: [], externalLinkRisk: "No repository evidence of inbound external links; runtime evidence is absent.",
  tokenCompatibilityRisk: "Not token-addressed.", runtimeEvidence: [], evidenceGaps: ["No production telemetry or runtime observation is available."],
  prerequisites: ["Collect the runtime evidence described in the decision matrix."], observationPeriod: "Minimum 30 consecutive production days, including a billing boundary.",
  ...entry,
});

export const DEPRECATION_CANDIDATES = [
  candidate({ id: "backup-customers-table", kind: "file", path: "app/components/CustomersTable.backup.tsx", repositoryPaths: [], historicalPaths: ["app/components/CustomersTable.backup.tsx"], repositoryState: "removed", category: "backup", currentStatus: "Removed from the repository after tracked-file static analysis found no importer, barrel export, dynamic load, test, script or route reference.", proposedDecision: "remove-after-evidence", confidence: "high", risk: "medium", owner: "CRM", documentationReferences: [ref("docs/deprecation-evidence-registry.md", 26, "Safe Cleanup 1 tombstone records the tracked-file evidence and removal disposition.")], rollbackPlan: "Restore the file from the removal commit.", notes: "Historical path only; removed from the working tree. Exact-symbol and path scan finds only the definition; the active CustomersTable remains separate." }),
  candidate({ id: "backup-sidebar", kind: "file", path: "app/components/Sidebar.backup.tsx", repositoryPaths: [], historicalPaths: ["app/components/Sidebar.backup.tsx"], repositoryState: "removed", category: "backup", currentStatus: "Removed from the repository after tracked-file static analysis found no importer, barrel export, dynamic load, test, script or route reference.", proposedDecision: "remove-after-evidence", confidence: "high", risk: "high", owner: "Platform UI", documentationReferences: [ref("docs/deprecation-evidence-registry.md", 26, "Safe Cleanup 1 tombstone records the tracked-file evidence and removal disposition.")], rollbackPlan: "Restore the file from the removal commit.", notes: "Historical path only; removed from the working tree. No caller was found. This evidence does not authorize changing the active Sidebar." }),
  candidate({ id: "settings-modules", kind: "route", path: "/settings/modules", repositoryPaths: ["app/settings/modules/page.tsx", "app/components/settings/ModulesSettingsClient.tsx"], category: "placeholder", currentStatus: "Manifest-classified placeholder backed by a client component.", proposedDecision: "hide-from-standard-navigation", confidence: "high", risk: "high", owner: "Platform", navigationReferences: [ref("app/system/page.tsx", 39, "System page links directly to Modules.")], rollbackPlan: "Restore the navigation entry if it is changed in a later PR.", notes: "The page labels functionality as under development; it is not empty, and this PR does not hide it." }),
  candidate({ id: "api-admin-test", kind: "api", path: "/api/admin/test", repositoryPaths: ["app/api/admin/test/route.ts"], category: "diagnostic-api", currentStatus: "Diagnostic endpoint; no exact static caller found outside its definition.", proposedDecision: "remove-after-evidence", confidence: "high", risk: "high", owner: "Platform", rollbackPlan: "Restore the endpoint from the removal commit and re-deploy.", notes: "Static absence cannot detect external scripts or manually issued requests." }),
  candidate({ id: "ui-lab", kind: "route", path: "/ui-lab", repositoryPaths: ["app/ui-lab/page.tsx", "app/ui-lab/ui-lab.module.css"], category: "development-lab", currentStatus: "Restricted design-system evaluation route.", proposedDecision: "hide-from-standard-navigation", confidence: "high", risk: "low", owner: "Design System", rollbackPlan: "Restore any future navigation exposure; route remains recoverable from Git.", notes: "Manifest audience is developer and classification is lab; runtime usage is unknown." }),
  candidate({ id: "ui-lab-platinum", kind: "route", path: "/ui-lab/platinum", repositoryPaths: ["app/ui-lab/platinum/page.tsx", "app/ui-lab/platinum/PlatinumDemo.tsx", "app/ui-lab/platinum/demo-data.ts"], category: "development-lab", currentStatus: "Platinum Foundation reference route.", proposedDecision: "retain", confidence: "high", risk: "medium", owner: "Design System", rollbackPlan: "Revert any later disposition commit.", notes: "It is a reference implementation, not evidence that Foundation assets can be removed." }),
  candidate({ id: "test-gate", kind: "route", path: "/test-gate", repositoryPaths: ["app/test-gate/page.tsx"], category: "hardware-diagnostic", currentStatus: "Restricted gate diagnostic UI.", proposedDecision: "protected-do-not-touch", confidence: "high", risk: "critical", owner: "Access Control", apiDependencies: ["/api/gate/test"], hardwareDependencies: ["Bridge C#", "DNake", "KT02.3", "turnstile"], rollbackPlan: "No change is authorized; escalate to Access Control owners.", notes: "Hardware diagnostics require device and Bridge validation, which static analysis cannot provide." }),
  candidate({ id: "v2-customers", kind: "route", path: "/v2/customers", repositoryPaths: ["app/v2/customers/page.tsx"], category: "customer-prototype", currentStatus: "Restricted prototype consuming the V2 API and components.", proposedDecision: "merge-after-parity", confidence: "high", risk: "critical", owner: "CRM", apiDependencies: ["/api/bodygate-v2/customers"], dataDependencies: ["customers"], rollbackPlan: "Keep V2 route/API available until parity and rollback acceptance are signed off.", notes: "Not removable: it has an API contract and distinct presentation components; feature parity is unproven." }),
  candidate({ id: "api-v2-customers", kind: "api", path: "/api/bodygate-v2/customers", repositoryPaths: ["app/api/bodygate-v2/customers/route.ts"], category: "customer-prototype-api", currentStatus: "API called by Customers V2.", proposedDecision: "merge-after-parity", confidence: "high", risk: "critical", owner: "CRM", directReferences: [ref("app/v2/customers/page.tsx", 45, "Fetches the V2 customer endpoint.")], dataDependencies: ["customers"], rollbackPlan: "Preserve endpoint while V2 route is available; revert consolidation if contract checks fail.", notes: "API consolidation requires response and error-contract parity." }),
  candidate({ id: "access-compatibility", kind: "route", path: "/access", repositoryPaths: ["app/access/page.tsx"], category: "access-compatibility", currentStatus: "Legacy compatibility route redirecting to access-control.", proposedDecision: "protected-do-not-touch", confidence: "high", risk: "critical", owner: "Access Control", externalLinkRisk: "Bookmarks, kiosks and operator procedures may use this legacy URL.", hardwareDependencies: ["Bridge C#", "turnstile"], rollbackPlan: "Retain the compatibility URL; revert only with Access Control approval.", notes: "Compatibility usage cannot be excluded by repository navigation analysis." }),
  candidate({ id: "access-check-public", kind: "api", path: "/access/check", repositoryPaths: ["app/access/check/route.ts"], category: "access-endpoint", currentStatus: "Non-API-namespace GET endpoint returning an HTML access result.", proposedDecision: "protected-do-not-touch", confidence: "high", risk: "critical", owner: "Access Control", indirectReferences: [ref("app/api/dnake/event/route.ts", 227, "Calls the distinct /api/access/check endpoint."), ref("bridge/bridge-v2/Program.cs", 30, "Bridge targets the distinct /api/access/check endpoint.")], hardwareDependencies: ["Bridge C#", "badge readers", "turnstile"], rollbackPlan: "Keep endpoint stable; restore immediately on device regression.", notes: "It is not equivalent to /api/access/check: path, methods, callers and response media differ." }),
  candidate({ id: "pass-token", kind: "route", path: "/pass/[token]", repositoryPaths: ["app/pass/[token]/page.tsx"], category: "public-token-route", currentStatus: "Public token-scoped digital pass.", proposedDecision: "protected-do-not-touch", confidence: "high", risk: "critical", owner: "Digital Credentials", tokenCompatibilityRisk: "Already distributed URLs and persisted tokens may remain valid outside repository visibility.", externalLinkRisk: "Links may exist in customer wallets, messages, QR codes and bookmarks.", dataDependencies: ["digital pass tokens", "customers"], rollbackPlan: "Retain the route and prior token resolver; restore immediately if any issued token fails.", notes: "Removal requires validation of the full population of previously issued tokens." }),
  candidate({ id: "mobile-token", kind: "route", path: "/mobile/[token]", repositoryPaths: ["app/mobile/[token]/page.tsx", "app/mobile/layouts.tsx"], category: "public-token-route", currentStatus: "Public token-scoped customer mobile experience.", proposedDecision: "protected-do-not-touch", confidence: "high", risk: "critical", owner: "Digital Credentials", tokenCompatibilityRisk: "Issued customer tokens are externally held and cannot be enumerated statically.", externalLinkRisk: "Links may exist in customer messages and bookmarks.", dataDependencies: ["mobile tokens", "customers"], rollbackPlan: "Retain route and token compatibility; restore immediately on validation failure.", notes: "No removal decision is permitted without issued-token compatibility evidence." }),
  candidate({ id: "api-customers-create", kind: "api", path: "/api/customers/create", repositoryPaths: ["app/api/customers/create/route.ts"], category: "customer-write-api", currentStatus: "Customer creation endpoint.", proposedDecision: "merge-after-parity", confidence: "medium", risk: "critical", owner: "CRM", dataDependencies: ["customers", "subscriptions", "payments"], rollbackPlan: "Keep both creation contracts until transactional parity is proven.", notes: "Write behavior and external callers require runtime and contract evidence." }),
  candidate({ id: "api-customers-create-platinum", kind: "api", path: "/api/customers/create-platinum", repositoryPaths: ["app/api/customers/create-platinum/route.ts"], category: "customer-write-api", currentStatus: "Platinum customer creation endpoint called by onboarding UI.", proposedDecision: "merge-after-parity", confidence: "high", risk: "critical", owner: "CRM", directReferences: [ref("app/customers/new/page.tsx", 178, "Onboarding fetch caller."), ref("app/customers/new/page.tsx", 315, "Onboarding postJson caller.")], dataDependencies: ["customers", "subscriptions", "payments"], rollbackPlan: "Retain endpoint and switch caller back if consolidated creation regresses.", notes: "Similar intent is not transactional or validation parity." }),
  candidate({ id: "api-medical-certificate-by-id", kind: "api", path: "/api/customers/[id]/medical-certificate", repositoryPaths: ["app/api/customers/[id]/medical-certificate/route.ts"], category: "medical-certificate-api", currentStatus: "Customer-scoped PATCH endpoint with a static UI caller.", proposedDecision: "merge-after-parity", confidence: "high", risk: "critical", owner: "CRM", directReferences: [ref("app/customers/components/CustomerDocumentRows.tsx", 94, "PATCH caller.")], dataDependencies: ["customers", "medical certificate metadata"], rollbackPlan: "Keep both endpoint families until payload and storage parity are proven.", notes: "One of two certificate API families; caller and payload differ." }),
  candidate({ id: "api-medical-certificate-update", kind: "api", path: "/api/customers/update-medical-certificate", repositoryPaths: ["app/api/customers/update-medical-certificate/route.ts"], category: "medical-certificate-api", currentStatus: "Legacy-style update endpoint with a static UI caller.", proposedDecision: "merge-after-parity", confidence: "high", risk: "critical", owner: "CRM", directReferences: [ref("app/customers/components/MedicalCertificateCard.tsx", 135, "Fetch caller.")], dataDependencies: ["customers", "medical-certificates storage"], rollbackPlan: "Retain endpoint and caller adapter until payload, storage and errors match.", notes: "The two certificate APIs are not interchangeable without an adapter and migration plan." }),
  candidate({ id: "bodygate-v2-components", kind: "component-family", path: "app/components/bodygate-v2", repositoryPaths: ["app/components/bodygate-v2/BGButton.tsx", "app/components/bodygate-v2/BGCustomerCard.tsx", "app/components/bodygate-v2/bodygate-v2.css"], category: "prototype-components", currentStatus: "V2-specific component family; active members are imported by Customers V2 and the removed metric remains recorded separately as a tombstone.", proposedDecision: "merge-after-parity", confidence: "high", risk: "high", owner: "Design System", rollbackPlan: "Preserve V2 components until adapters pass visual and behavior parity checks.", notes: "Naming overlap with UI primitives is not implementation parity." }),
  candidate({ id: "unreferenced-bgmetriccard", kind: "component", path: "app/components/bodygate-v2/BGMetricCard.tsx", repositoryPaths: [], historicalPaths: ["app/components/bodygate-v2/BGMetricCard.tsx"], repositoryState: "removed", category: "no-static-import", currentStatus: "Removed from the repository after tracked-file static analysis found no importer, barrel export, dynamic load, test, script or route reference.", proposedDecision: "remove-after-evidence", confidence: "high", risk: "medium", owner: "Design System", documentationReferences: [ref("docs/deprecation-evidence-registry.md", 26, "Safe Cleanup 1 tombstone records the tracked-file evidence and removal disposition.")], rollbackPlan: "Restore component and stylesheet usage from the removal commit.", notes: "Historical path only; removed from the working tree. Dynamic or copied consumption outside tracked files remains an evidence gap." }),
  candidate({ id: "unreferenced-ui-content-grid", kind: "component", path: "app/components/ui/BGContentGrid.tsx", repositoryPaths: [], historicalPaths: ["app/components/ui/BGContentGrid.tsx"], repositoryState: "removed", category: "no-static-import", currentStatus: "Removed from the repository after tracked-file static analysis found no importer, barrel export, dynamic load, test, script or route reference.", proposedDecision: "remove-after-evidence", confidence: "high", risk: "low", owner: "Design System", documentationReferences: [ref("docs/deprecation-evidence-registry.md", 26, "Safe Cleanup 1 tombstone records the tracked-file evidence and removal disposition.")], rollbackPlan: "Restore component from the removal commit.", notes: "Historical path only; removed from the working tree. Definition-only exact-symbol result." }),
  candidate({ id: "unreferenced-ui-form-panel", kind: "component", path: "app/components/ui/BGFormPanel.tsx", repositoryPaths: [], historicalPaths: ["app/components/ui/BGFormPanel.tsx"], repositoryState: "removed", category: "no-static-import", currentStatus: "Removed from the repository after tracked-file static analysis found no importer, barrel export, dynamic load, test, script or route reference.", proposedDecision: "remove-after-evidence", confidence: "high", risk: "low", owner: "Design System", documentationReferences: [ref("docs/deprecation-evidence-registry.md", 26, "Safe Cleanup 1 tombstone records the tracked-file evidence and removal disposition.")], rollbackPlan: "Restore component from the removal commit.", notes: "Historical path only; removed from the working tree. Definition-only exact-symbol result." }),
  candidate({ id: "unreferenced-ui-inline-alert", kind: "component", path: "app/components/ui/BGInlineAlert.tsx", repositoryPaths: [], historicalPaths: ["app/components/ui/BGInlineAlert.tsx"], repositoryState: "removed", category: "no-static-import", currentStatus: "Removed from the repository after tracked-file static analysis found no importer, barrel export, dynamic load, test, script or route reference.", proposedDecision: "remove-after-evidence", confidence: "high", risk: "low", owner: "Design System", documentationReferences: [ref("docs/deprecation-evidence-registry.md", 26, "Safe Cleanup 1 tombstone records the tracked-file evidence and removal disposition.")], rollbackPlan: "Restore component from the removal commit.", notes: "Historical path only; removed from the working tree. Definition-only exact-symbol result." }),
  candidate({ id: "unreferenced-ui-premium-tabs", kind: "component", path: "app/components/ui/BGPremiumTabs.tsx", repositoryPaths: [], historicalPaths: ["app/components/ui/BGPremiumTabs.tsx"], repositoryState: "removed", category: "no-static-import", currentStatus: "Removed from the repository after tracked-file static analysis found no importer, barrel export, dynamic load, test, script or route reference.", proposedDecision: "remove-after-evidence", confidence: "high", risk: "medium", owner: "Design System", documentationReferences: [ref("docs/deprecation-evidence-registry.md", 26, "Safe Cleanup 1 tombstone records the tracked-file evidence and removal disposition.")], rollbackPlan: "Restore component from the removal commit.", notes: "Historical path only; removed from the working tree. Definition-only exact-symbol result; premium naming raises adapter risk." }),
  candidate({ id: "ui-duplicate-primitives", kind: "component-family", path: "app/components/ui", repositoryPaths: ["app/components/ui/BGButton.tsx", "app/components/ui/BGCard.tsx", "app/components/ui/BGStatCard.tsx"], category: "overlapping-ui-primitives", currentStatus: "Active UI primitives overlap conceptually with V2 Button/Card/MetricCard.", proposedDecision: "merge-after-parity", confidence: "medium", risk: "high", owner: "Design System", rollbackPlan: "Keep adapters and both implementations until prop, state and visual parity is approved.", notes: "Duplication is conceptual, not byte-identical; adapters are required instead of deletion." }),
] as const satisfies readonly DeprecationCandidate[];
