"use client"

import { useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { Activity, AlertTriangle, ArrowRight, Ban, Bell, CreditCard, DoorOpen, RefreshCw, ShieldAlert, UserPlus, Users } from "lucide-react"
import { BGEmptyState } from "@/components/bodygate-ui"
import { adaptDashboardOverview } from "@/architecture/platinum-runtime-adapters"
import styles from "./dashboard.module.css"

type DashboardAccessItem = { id?: string | number | null; allowed?: boolean | null; created_at?: string | null; display_name?: string | null; customer_name?: string | null; staff_name?: string | null; full_name?: string | null; first_name?: string | null; last_name?: string | null; controller_code?: string | null; badge_code?: string | null; reason?: string | null }
type DashboardAlertItem = { id?: string | number | null; customer_name?: string | null; first_name?: string | null; last_name?: string | null; customer_id?: string | null; ends_at?: string | null; medical_certificate_end?: string | null }
type DashboardOverview = { ok: boolean; generated_at: string; kpis: { active_customers: number; accesses_today: number; denied_today: number; revenue_today: number; revenue_month: number; active_blocks: number }; bridge: { status: string; last_seen_at: string | null; raw: unknown }; alerts: { expired_medical: DashboardAlertItem[]; expiring_medical: DashboardAlertItem[]; expired_subscriptions: DashboardAlertItem[]; expiring_subscriptions: DashboardAlertItem[] }; latest_access: DashboardAccessItem[] }

const missing = "Dato non disponibile"
function euro(value: number | null) { return value === null ? missing : new Intl.NumberFormat("it-IT", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(value) }
function dateTime(value?: string | null) { return value ? new Date(value).toLocaleString("it-IT", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" }) : "—" }
function person(item: DashboardAccessItem) { return item.display_name || item.customer_name || item.staff_name || item.full_name || `${item.first_name || ""} ${item.last_name || ""}`.trim() || `Codice: ${item.controller_code || item.badge_code || "—"}` }

export default function DashboardPage() {
  const [data, setData] = useState<DashboardOverview | null>(null); const [loading, setLoading] = useState(true); const [errorMessage, setErrorMessage] = useState("")
  async function loadDashboard() { try { setErrorMessage(""); const res = await fetch("/api/dashboard/overview", { cache: "no-store" }); const json = await res.json(); if (!res.ok || !json.ok) throw new Error(json.error || "Errore caricamento dashboard."); setData(json) } catch (error: unknown) { setErrorMessage(error instanceof Error ? error.message : "Errore imprevisto.") } finally { setLoading(false) } }
  useEffect(() => { void Promise.resolve().then(loadDashboard); const timer = setInterval(loadDashboard, 30000); return () => clearInterval(timer) }, [])
  const view = useMemo(() => adaptDashboardOverview(data), [data]); const latestAccess = Array.isArray(data?.latest_access) ? data.latest_access : null
  const alertLists = { expiredMedical: Array.isArray(data?.alerts?.expired_medical) ? data.alerts.expired_medical : null, expiringMedical: Array.isArray(data?.alerts?.expiring_medical) ? data.alerts.expiring_medical : null, expiredSubscriptions: Array.isArray(data?.alerts?.expired_subscriptions) ? data.alerts.expired_subscriptions : null, expiringSubscriptions: Array.isArray(data?.alerts?.expiring_subscriptions) ? data.alerts.expiring_subscriptions : null }
  const alertsComplete = Object.values(view.alertCounts).every(value => value !== null) && view.kpis.activeBlocks !== null
  const totalAlerts = alertsComplete ? Object.values(view.alertCounts).reduce<number>((total, value) => total + (value ?? 0), view.kpis.activeBlocks ?? 0) : null
  const alertSummary = totalAlerts === null ? "Da verificare" : `${totalAlerts} priorità da gestire`
  const bridgeOnline = view.bridgeStatus === "online" || view.bridgeStatus === "ok"
  const primary = [
    { label: "Clienti attivi", value: view.kpis.activeCustomers, note: "Anagrafiche operative", icon: Users },
    { label: "Ingressi oggi", value: view.kpis.accessesToday, note: "Accessi registrati", icon: DoorOpen },
    { label: "Priorità aperte", value: totalAlerts, note: "Scadenze, certificati e blocchi", icon: AlertTriangle },
    { label: "Incassi oggi", value: euro(view.kpis.revenueToday), note: "Totale giornaliero", icon: CreditCard, money: true },
  ]
  const deadlines = [...(alertLists.expiredSubscriptions ?? []), ...(alertLists.expiringSubscriptions ?? []), ...(alertLists.expiredMedical ?? []), ...(alertLists.expiringMedical ?? [])]
  return <div className={styles.dashboard}>
    <section className={styles.hero}><div><p className={styles.eyebrow}>Centro di controllo</p><h1>Buongiorno, Operatore</h1><p>Panoramica delle attività reali del club, delle priorità di reception e dello stato operativo.</p></div><div className={styles.heroActions}><Link href="/reception" className={styles.button}>Apri Reception <ArrowRight /></Link><button className={`${styles.button} ${styles.primary}`} onClick={loadDashboard} disabled={loading}><RefreshCw className={loading ? styles.spin : ""} />Aggiorna</button></div></section>
    {errorMessage ? <div className={styles.error} role="alert"><ShieldAlert />{errorMessage}</div> : null}
    <section className={styles.kpiGrid} aria-label="Indicatori principali" data-primary-kpi-count="4">{primary.map(({ label, value, note, icon: Icon, money }) => <article className={styles.kpi} key={label}><div className={styles.kpiTop}><div><span className={styles.kpiLabel}>{label}</span><strong className={`${styles.kpiValue} ${money ? styles.money : ""}`}>{typeof value === "number" ? value : value ?? missing}</strong></div><span className={styles.kpiIcon}><Icon /></span></div><span className={styles.kpiNote}>{note}</span></article>)}</section>
    <div className={styles.workspace}><section className={styles.card}><header className={styles.panelHeader}><div><h2>Attività recente</h2><p>Ultimi accessi rilevati dai sistemi operativi.</p></div><span className={styles.badge}>{latestAccess?.length ?? "—"} eventi</span></header>{latestAccess === null ? <div className={styles.empty}><BGEmptyState title={missing} description="Gli accessi non sono presenti nella risposta." /></div> : latestAccess.length === 0 ? <div className={styles.empty}><BGEmptyState title="Nessun accesso recente" description="Le nuove attività appariranno qui." /></div> : <div className={styles.tableWrap}><table><thead><tr><th>Esito</th><th>Persona</th><th>Dettaglio</th><th>Ora</th></tr></thead><tbody>{latestAccess.map(item => <tr key={item.id || `${item.created_at}-${person(item)}`}><td><span className={`${styles.result} ${item.allowed ? styles.allowed : styles.denied}`}>{item.allowed ? "Consentito" : "Negato"}</span></td><td><strong>{person(item)}</strong></td><td>{item.reason || "Nessun motivo"}</td><td>{dateTime(item.created_at)}</td></tr>)}</tbody></table></div>}</section>
      <aside className={styles.sideStack}><section className={`${styles.card} ${styles.priority}`}><span className={styles.priorityIcon}><AlertTriangle /></span><div><strong>{alertSummary}</strong><p>Controlla scadenze, certificati e blocchi attivi.</p><Link href="/notifications">Apri notifiche <ArrowRight /></Link></div></section><section className={styles.card}><header className={styles.panelHeader}><div><h2>Azioni rapide</h2><p>Operazioni frequenti</p></div></header><div className={styles.quickGrid}><Link href="/customers/new"><UserPlus />Nuovo cliente</Link><Link href="/reception"><DoorOpen />Reception</Link><Link href="/payments"><CreditCard />Nuovo incasso</Link><Link href="/notifications"><Bell />Scadenze</Link></div></section></aside>
    </div>
    <section className={styles.secondaryGrid} aria-label="Indicatori secondari"><article className={styles.card}><header className={styles.panelHeader}><div><h2>Stato operativo</h2><p>Indicatori tecnici e anomalie di giornata.</p></div></header><div className={styles.metrics}><div><Ban /><span>Accessi negati oggi</span><strong>{view.kpis.deniedToday ?? missing}</strong></div><div><ShieldAlert /><span>Blocchi attivi</span><strong>{view.kpis.activeBlocks ?? missing}</strong></div><div><Activity /><span>Bridge</span><strong className={bridgeOnline ? styles.online : styles.offline}>{view.bridgeStatus ?? "Da verificare"}</strong></div></div></article><article className={styles.card}><header className={styles.panelHeader}><div><h2>Incassi</h2><p>Riepilogo economico disponibile.</p></div></header><div className={styles.revenue}><span>Oggi <strong className={styles.money}>{euro(view.kpis.revenueToday)}</strong></span><span>Mese <strong className={styles.money}>{euro(view.kpis.revenueMonth)}</strong></span></div></article></section>
    <section className={styles.card}><header className={styles.panelHeader}><div><h2>Scadenze e certificati</h2><p>Elementi scaduti o in scadenza restituiti dalla Dashboard.</p></div><Link href="/notifications" className={styles.textLink}>Vedi tutte <ArrowRight /></Link></header>{Object.values(alertLists).some(value => value === null) ? <div className={styles.empty}><BGEmptyState title={missing} description="Una o più categorie non sono presenti nella risposta." /></div> : deadlines.length === 0 ? <div className={styles.empty}><BGEmptyState title="Nessuna scadenza" description="Abbonamenti e certificati risultano sotto controllo." /></div> : <div className={styles.deadlines}>{deadlines.slice(0, 8).map((item, index) => { const name = item.customer_name || `${item.first_name || ""} ${item.last_name || ""}`.trim() || item.customer_id || "Cliente da verificare"; return <div key={`${item.id}-${index}`}><AlertTriangle /><span><strong>{name}</strong><small>Scadenza: {dateTime(item.ends_at || item.medical_certificate_end)}</small></span></div> })}</div>}</section>
  </div>
}
