import { createClient } from "@supabase/supabase-js";
import { NextResponse } from "next/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type Risk = "critical" | "medium" | "low" | "ok";
type Source = "access_credentials" | "customer_badges" | "staff_access_credentials" | "customers.badge_code" | "customers.controller_code";
type Owner = { type: "customer" | "staff" | "none"; id: string | null; name: string | null; active: boolean | null };
type Credential = { id: string | null; code: string; normalized: string; source: Source; field: string; active: boolean | null; status: string | null; owner: Owner; legacy: boolean };
type AuditItem = { id: string; code: string; risk: Risk; category: string; source: string; owner: string; credential_status: string; owner_status: string; explanation: string; recommended_action: string; debug_url: string; technical: Record<string, unknown> };

function getSupabaseClient() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!supabaseUrl) throw new Error("NEXT_PUBLIC_SUPABASE_URL mancante");
  if (!supabaseServiceKey) throw new Error("SUPABASE_SERVICE_ROLE_KEY mancante");
  return createClient(supabaseUrl, supabaseServiceKey, { auth: { persistSession: false, autoRefreshToken: false } });
}
async function safeSelect<T>(label: string, query: PromiseLike<{ data: T | null; error: any }>, warnings: string[]) { const { data, error } = await query; if (error) warnings.push(`${label}: ${error.message}`); return error ? null : data; }
const normalizeCode = (value: unknown) => String(value || "").trim();
const normalizedKey = (value: unknown) => normalizeCode(value).toUpperCase();
function nameOf(row: any) { return String(row?.full_name || `${row?.first_name || ""} ${row?.last_name || ""}`).trim() || null; }
function isActiveRow(row: any) { if (typeof row?.is_active === "boolean") return row.is_active; if (typeof row?.active === "boolean") return row.active; if (row?.status) return String(row.status).toLowerCase() === "active"; return null; }
function isOwnerActive(row: any) { if (!row) return null; if (typeof row.is_active === "boolean") return row.is_active; if (typeof row.active === "boolean") return row.active; if (row.status) return !["inactive", "disabled", "archived", "deleted"].includes(String(row.status).toLowerCase()); return true; }
function isSuspicious(owner: Owner, code: string) { return /\b(test|prova|xenia|demo|fake|dummy)\b/i.test(`${owner.name || ""} ${code}`); }
function statusLabel(value: boolean | null, status: string | null) { return status || (value === null ? "legacy/non tracciato" : value ? "attiva" : "inattiva"); }
function ownerLabel(owner: Owner) { return owner.id ? `${owner.type === "staff" ? "Staff" : "Cliente"}: ${owner.name || owner.id}` : "Proprietario mancante"; }
function add(items: AuditItem[], params: Omit<AuditItem, "id" | "debug_url">) { items.push({ ...params, id: `${params.category}-${params.source}-${params.code}-${items.length}`, debug_url: `/access-control/debug?code=${encodeURIComponent(params.code)}` }); }

export async function GET() {
  try {
    const warnings: string[] = [];
    const supabase = getSupabaseClient();
    const [customers, staff, accessCredentials, customerBadges, staffCredentials] = await Promise.all([
      safeSelect<any[]>("Lettura customers", supabase.from("customers").select("id, first_name, last_name, full_name, badge_code, controller_code, is_active, active, status"), warnings),
      safeSelect<any[]>("Lettura staff_users", supabase.from("staff_users").select("id, first_name, last_name, full_name, email, is_active, active, status"), warnings),
      safeSelect<any[]>("Lettura access_credentials", supabase.from("access_credentials").select("id, customer_id, code, controller_code, type, status, is_active, active, created_at"), warnings),
      safeSelect<any[]>("Lettura customer_badges", supabase.from("customer_badges").select("id, customer_id, badge_code, code, is_active, active, status, created_at"), warnings),
      safeSelect<any[]>("Lettura staff_access_credentials", supabase.from("staff_access_credentials").select("id, staff_user_id, staff_id, code, controller_code, type, status, is_active, active, created_at"), warnings),
    ]);
    const customerById = new Map((customers || []).map((c) => [String(c.id), c]));
    const staffById = new Map((staff || []).map((s) => [String(s.id), s]));
    const credentials: Credential[] = [];
    for (const row of accessCredentials || []) { const customer = row.customer_id ? customerById.get(String(row.customer_id)) : null; for (const field of ["code", "controller_code"] as const) { const code = normalizeCode(row[field]); if (code) credentials.push({ id: row.id ?? null, code, normalized: normalizedKey(code), source: "access_credentials", field, active: isActiveRow(row), status: row.status ?? null, legacy: false, owner: { type: "customer", id: row.customer_id ?? null, name: nameOf(customer), active: isOwnerActive(customer) } }); } }
    for (const row of customerBadges || []) { const code = normalizeCode(row.badge_code || row.code); const customer = row.customer_id ? customerById.get(String(row.customer_id)) : null; if (code) credentials.push({ id: row.id ?? null, code, normalized: normalizedKey(code), source: "customer_badges", field: row.badge_code ? "badge_code" : "code", active: isActiveRow(row), status: row.status ?? null, legacy: false, owner: { type: "customer", id: row.customer_id ?? null, name: nameOf(customer), active: isOwnerActive(customer) } }); }
    for (const row of staffCredentials || []) { const staffId = row.staff_user_id || row.staff_id || null; const staffOwner = staffId ? staffById.get(String(staffId)) : null; for (const field of ["code", "controller_code"] as const) { const code = normalizeCode(row[field]); if (code) credentials.push({ id: row.id ?? null, code, normalized: normalizedKey(code), source: "staff_access_credentials", field, active: isActiveRow(row), status: row.status ?? null, legacy: false, owner: { type: "staff", id: staffId, name: nameOf(staffOwner), active: isOwnerActive(staffOwner) } }); } }
    for (const row of customers || []) for (const [field, source] of [["badge_code", "customers.badge_code"], ["controller_code", "customers.controller_code"]] as const) { const code = normalizeCode(row[field]); if (code) credentials.push({ id: row.id ?? null, code, normalized: normalizedKey(code), source: source as Source, field, active: null, status: "legacy", legacy: true, owner: { type: "customer", id: row.id ?? null, name: nameOf(row), active: isOwnerActive(row) } }); }

    const items: AuditItem[] = [];
    const byCode = new Map<string, Credential[]>(); const badgeByCustomer = new Map<string, Credential[]>();
    for (const c of credentials) { byCode.set(c.normalized, [...(byCode.get(c.normalized) || []), c]); if (c.source === "customer_badges" && c.owner.id) badgeByCustomer.set(String(c.owner.id), [...(badgeByCustomer.get(String(c.owner.id)) || []), c]); }
    for (const [code, rows] of byCode) { const sources = new Set(rows.map((r) => r.source)); const customersSet = new Set(rows.filter((r) => r.owner.type === "customer" && r.owner.id).map((r) => r.owner.id)); const staffSet = new Set(rows.filter((r) => r.owner.type === "staff" && r.owner.id).map((r) => r.owner.id)); if (rows.length > 1) add(items, { code: rows[0].code, risk: staffSet.size && customersSet.size ? "critical" : "medium", category: staffSet.size && customersSet.size ? "Cliente/Staff" : "Duplicato", source: [...sources].join(", "), owner: rows.map((r) => ownerLabel(r.owner)).join(" · "), credential_status: rows.map((r) => statusLabel(r.active, r.status)).join(" · "), owner_status: rows.map((r) => r.owner.active === false ? "inattivo" : "attivo/nd").join(" · "), explanation: staffSet.size && customersSet.size ? "Lo stesso codice è presente sia su credenziali cliente sia su credenziali staff." : "Lo stesso codice compare più volte nella stessa fonte o su fonti diverse.", recommended_action: staffSet.size && customersSet.size ? "Rimuovere duplicazione tra cliente e staff" : "Verificare quale record deve rimanere valido e disattivare i duplicati non necessari", technical: { normalized_code: code, records: rows } }); if (customersSet.size > 1) add(items, { code: rows[0].code, risk: "critical", category: "Duplicato cliente", source: [...sources].join(", "), owner: [...customersSet].join(", "), credential_status: "conflitto", owner_status: "più clienti", explanation: "Lo stesso codice risulta assegnato a più clienti.", recommended_action: "Assegnare il codice a un solo cliente e bonificare gli altri record", technical: { records: rows } }); }
    for (const c of credentials) { if (!c.owner.id || (c.owner.id && c.owner.active === null && !c.owner.name)) add(items, { code: c.code, risk: "critical", category: "Senza proprietario", source: c.source, owner: ownerLabel(c.owner), credential_status: statusLabel(c.active, c.status), owner_status: "mancante", explanation: "La credenziale non ha un proprietario valido o il record collegato non esiste.", recommended_action: "Collegare la credenziale a un proprietario valido o disattivarla", technical: c as unknown as Record<string, unknown> }); if (c.active === true && c.owner.active === false) add(items, { code: c.code, risk: "critical", category: "Stato incoerente", source: c.source, owner: ownerLabel(c.owner), credential_status: "attiva", owner_status: "inattivo", explanation: `${c.owner.type === "staff" ? "Staff" : "Cliente"} inattivo con credenziale ancora attiva.`, recommended_action: c.owner.type === "staff" ? "Verificare staff inattivo con credenziale ancora attiva" : "Verificare cliente inattivo con badge ancora attivo", technical: c as unknown as Record<string, unknown> }); if (c.active === false && c.owner.active === true) add(items, { code: c.code, risk: "medium", category: "Stato incoerente", source: c.source, owner: ownerLabel(c.owner), credential_status: "inattiva", owner_status: "attivo", explanation: "Proprietario attivo con credenziale registrata come inattiva.", recommended_action: "Verificare se la reception deve riemettere o riattivare una credenziale valida", technical: c as unknown as Record<string, unknown> }); if (c.legacy) add(items, { code: c.code, risk: c.source === "customers.controller_code" ? "medium" : "low", category: "Legacy", source: c.source, owner: ownerLabel(c.owner), credential_status: "legacy/non tracciato", owner_status: c.owner.active === false ? "inattivo" : "attivo/nd", explanation: c.source === "customers.controller_code" ? "customers.controller_code presente ma non tracciato nelle tabelle credenziali dedicate." : "Codice legacy su customers potenzialmente ancora utilizzabile.", recommended_action: "Allineare il dato alle tabelle credenziali tracciate o confermare che sia solo storico", technical: c as unknown as Record<string, unknown> }); if (isSuspicious(c.owner, c.code)) add(items, { code: c.code, risk: c.active === true ? "medium" : "low", category: "Test/Sospetta", source: c.source, owner: ownerLabel(c.owner), credential_status: statusLabel(c.active, c.status), owner_status: c.owner.active === false ? "inattivo" : "attivo/nd", explanation: "Codice o proprietario sembrano collegati a TEST, Prova, Xenia, demo o dati simili.", recommended_action: "Disattivare credenziale test se non più utilizzata", technical: c as unknown as Record<string, unknown> }); }
    for (const customer of customers || []) { const badge = normalizeCode(customer.badge_code); const tracked = badgeByCustomer.get(String(customer.id)) || []; if (badge && tracked.length && !tracked.some((r) => normalizedKey(r.code) === normalizedKey(badge))) add(items, { code: badge, risk: "medium", category: "Badge non allineato", source: "customers.badge_code, customer_badges", owner: ownerLabel({ type: "customer", id: customer.id, name: nameOf(customer), active: isOwnerActive(customer) }), credential_status: "incoerente", owner_status: isOwnerActive(customer) === false ? "inattivo" : "attivo/nd", explanation: "customers.badge_code è diverso dai record customer_badges presenti per lo stesso cliente.", recommended_action: "Allineare customers.badge_code e customer_badges", technical: { customer, customer_badges: tracked } }); }
    const anomalousCodes = new Set(items.map((i) => `${i.code}|${i.source}`)); const ok = credentials.filter((c) => !anomalousCodes.has(`${c.code}|${c.source}`)).length;
    const summary = { total_credentials: credentials.length, critical: items.filter((i) => i.risk === "critical").length, medium: items.filter((i) => i.risk === "medium").length, low: items.filter((i) => i.risk === "low").length, duplicates: items.filter((i) => i.category.toLowerCase().includes("duplic")).length, suspicious: items.filter((i) => i.category === "Test/Sospetta").length, without_owner: items.filter((i) => i.category === "Senza proprietario").length, customer_staff_overlaps: items.filter((i) => i.category === "Cliente/Staff").length, ok_records: ok };
    return NextResponse.json({ summary, items, warnings, generated_at: new Date().toISOString(), diagnostic_only: true });
  } catch (error: unknown) { return NextResponse.json({ error: error instanceof Error ? error.message : "Errore audit credenziali", diagnostic_only: true }, { status: 500 }); }
}
