"use client"

import { AlertTriangle, ArrowUpRight, CalendarPlus, CircleAlert, Clock3, Download, FileText, Info, LoaderCircle, Plus, Search, UserPlus, Users } from "lucide-react"
import { BGDialog, PlatinumAppShell } from "@/components/bodygate-ui"
import { platinumCustomers, platinumKpis } from "./demo-data"
import styles from "@/components/bodygate-ui/platinum.module.css"

export default function PlatinumDemo() {
  return <PlatinumAppShell>
    <div className={styles.demoNotice}><Info aria-hidden="true" />Ambiente dimostrativo isolato: i dati mostrati non provengono dai sistemi operativi.</div>
    <section className={styles.pageIntro} aria-labelledby="platinum-title"><div><p className={styles.eyebrow}>Centro di controllo</p><h1 id="platinum-title" className={styles.pageTitle}>Buongiorno, Andrea</h1><p className={styles.pageSubtitle}>Una panoramica essenziale delle attività del club, con priorità operative e indicatori aggiornati.</p></div><div className={styles.actions}><button className={styles.button}><Download />Esporta riepilogo</button><BGDialog trigger={<button className={`${styles.button} ${styles.buttonPrimary}`}><Plus />Nuova attività</button>} title="Crea una nuova attività" description="Questa azione è solo dimostrativa e non modifica alcun dato operativo."><p className={styles.dialogText}>La fondazione Platinum usa dialog accessibili, con gestione del focus e chiusura da tastiera.</p></BGDialog></div></section>
    <section className={styles.kpiGrid} aria-label="Indicatori principali">{platinumKpis.map((kpi,index)=><article className={`${styles.card} ${styles.kpi}`} key={kpi.label}><div className={styles.kpiTop}><div><div className={styles.kpiLabel}>{kpi.label}</div><div className={styles.kpiValue}>{kpi.value}</div></div><div className={styles.kpiIcon}>{index===0?<Users />:index===1?<Clock3 />:index===2?<CircleAlert />:<ArrowUpRight />}</div></div><div className={`${styles.kpiNote} ${kpi.tone === "positive" ? styles.positive : ""}`}>{kpi.note}</div></article>)}</section>
    <div className={styles.workspace}><section className={styles.card}><div className={styles.panelHeader}><div><h2 className={styles.panelTitle}>Clienti da monitorare</h2><p className={styles.panelDescription}>Dati locali dimostrativi per la validazione dell’interfaccia.</p></div><button className={`${styles.button} ${styles.iconButton}`} aria-label="Cerca nei clienti"><Search /></button></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Cliente</th><th>Piano</th><th>Stato</th><th>Ultima attività</th></tr></thead><tbody>{platinumCustomers.map(customer=><tr key={customer.email}><td><div className={styles.customer}><span className={styles.customerInitials}>{customer.initials}</span><span><strong>{customer.name}</strong><span>{customer.email}</span></span></div></td><td>{customer.plan}</td><td><span className={`${styles.badge} ${styles[customer.tone]}`}>{customer.status}</span></td><td>{customer.activity}</td></tr>)}</tbody></table></div></section>
    <aside className={styles.sideStack} aria-label="Priorità e azioni"><section className={`${styles.card} ${styles.alert}`}><div className={styles.alertIcon}><AlertTriangle /></div><div><strong>7 rinnovi richiedono attenzione</strong><p>Contatta i clienti entro venerdì per proteggere il tasso di rinnovo.</p></div></section><section className={styles.card}><div className={styles.panelHeader}><div><h2 className={styles.panelTitle}>Azioni rapide</h2><p className={styles.panelDescription}>Scorciatoie dimostrative</p></div></div><div className={styles.quickGrid}><button className={styles.quickAction}><UserPlus />Nuovo cliente</button><button className={styles.quickAction}><CalendarPlus />Pianifica attività</button><button className={styles.quickAction}><FileText />Crea report</button><button className={styles.quickAction} disabled><Plus />Azione disabilitata</button></div></section></aside></div>
    <section className={styles.states} aria-label="Stati dell’interfaccia"><article className={`${styles.card} ${styles.state}`}><div><div className={styles.stateIcon}><Search /></div><h3>Nessun risultato</h3><p>Modifica i filtri o avvia una nuova ricerca.</p></div></article><article className={`${styles.card} ${styles.state}`} aria-label="Caricamento in corso"><div className={styles.skeleton}><LoaderCircle className={styles.stateIcon} /><span className={styles.skeletonLine} /><span className={styles.skeletonLine} /></div></article><article className={`${styles.card} ${styles.state}`}><div><div className={`${styles.stateIcon} ${styles.errorIcon}`}><CircleAlert /></div><h3>Dati non disponibili</h3><p>Riprova tra qualche istante. Nessuna modifica è stata applicata.</p></div></article></section>
  </PlatinumAppShell>
}
