import type { PlatinumScreenId } from "@/architecture/platinum-screen-registry"

type PreviewContent = {
  primaryAction: string
  metrics: readonly [string, string, string]
  columns: readonly [string, string, string, string]
  rows: readonly [readonly [string, string, string, string], readonly [string, string, string, string], readonly [string, string, string, string]]
  empty: string
}
const row = (subject: string, context: string, update: string, status: string) => [subject, context, update, status] as const
const content = (primaryAction: string, metrics: PreviewContent["metrics"], columns: PreviewContent["columns"], rows: PreviewContent["rows"], empty: string): PreviewContent => ({ primaryAction, metrics, columns, rows, empty })

export const PLATINUM_PREVIEW_CONTENT: Record<PlatinumScreenId, PreviewContent> = {
  dashboard: content("Nuova attività", ["Clienti attivi", "Priorità aperte", "Ingressi oggi"], ["Priorità", "Area", "Scadenza", "Stato"], [row("7 rinnovi", "Commerciale", "Oggi", "In attenzione"), row("3 certificati", "Clienti", "Domani", "Da verificare"), row("Turno serale", "Reception", "18:00", "Regolare")], "Nessuna priorità per il periodo selezionato."),
  reception: content("Registra ingresso", ["Ingressi oggi", "Attesi", "Verifiche"], ["Cliente", "Prenotazione", "Orario", "Accesso"], [row("Martina Rossi", "Pilates", "09:40", "Da verificare"), row("Luca Bianchi", "Sala pesi", "09:32", "Regolare"), row("Giulia Conti", "Corso mobility", "10:00", "Atteso")], "Nessun cliente in attesa alla reception."),
  notifications: content("Crea promemoria", ["Da leggere", "In scadenza", "Completate"], ["Notifica", "Destinatario", "Scadenza", "Priorità"], [row("Certificato medico", "Martina Rossi", "Oggi", "Alta"), row("Rinnovo annuale", "Luca Bianchi", "Domani", "Media"), row("Richiamo quota", "Giulia Conti", "25 agosto", "Bassa")], "Nessuna notifica corrisponde ai filtri."),
  "activity-center": content("Assegna attività", ["Aperte", "Assegnate a me", "Scadute"], ["Attività", "Responsabile", "Termine", "Stato"], [row("Verifica documento", "Sara · Reception", "10:30", "In corso"), row("Contatto rinnovo", "Marco · Vendite", "12:00", "Da iniziare"), row("Quadratura cassa", "Elena · Admin", "18:30", "Pianificata")], "La coda operativa è aggiornata."),
  customers: content("Nuovo cliente", ["Clienti attivi", "Nuovi questo mese", "Da verificare"], ["Cliente", "Abbonamento", "Ultima attività", "Stato"], [row("Martina Rossi", "Annuale Platinum", "Oggi, 09:40", "Da verificare"), row("Luca Bianchi", "Open 12 mesi", "Ieri, 18:12", "Regolare"), row("Giulia Conti", "Pilates 10 ingressi", "22 agosto", "In attenzione")], "Nessun cliente trovato. Modifica ricerca o filtri."),
  "customer-new": content("Salva bozza", ["Passaggi completati", "Consensi", "Documenti"], ["Sezione", "Compilazione", "Validazione", "Stato"], [row("Anagrafica", "8 di 8 campi", "Completa", "Regolare"), row("Contatti", "3 di 4 campi", "Email mancante", "Da verificare"), row("Consensi", "0 di 3", "Non avviata", "In attenzione")], "La bozza del nuovo cliente non contiene ancora dati."),
  "customer-detail": content("Aggiungi nota", ["Abbonamento", "Saldo", "Ultimo accesso"], ["Evento", "Dettaglio", "Data", "Esito"], [row("Accesso", "Reception principale", "Oggi, 09:40", "Da verificare"), row("Pagamento", "Secondo acconto", "15 febbraio", "Parziale"), row("Documento", "Certificato medico", "10 gennaio", "Valido")], "Non sono presenti eventi nella scheda cliente."),
  "customer-edit": content("Salva modifiche", ["Campi modificati", "Dati verificati", "Avvisi"], ["Campo", "Valore attuale", "Ultima modifica", "Stato"], [row("Telefono", "+39 ••• ••• 0142", "Oggi", "Modificato"), row("Email", "martina@example.test", "12 gennaio", "Verificato"), row("Indirizzo", "Dato dimostrativo", "10 gennaio", "Regolare")], "Non ci sono modifiche da salvare."),
  "customer-documents": content("Aggiungi documento", ["Documenti validi", "In scadenza", "Mancanti"], ["Documento", "Validità", "Scadenza", "Stato"], [row("Certificato medico", "12 mesi", "15 settembre", "In scadenza"), row("Documento identità", "Registrato", "12 giugno 2028", "Valido"), row("Consenso privacy", "Versione 3", "—", "Firmato")], "Nessun documento disponibile per il cliente."),
  "customer-history": content("Registra evento", ["Eventi", "Note operatore", "Variazioni"], ["Evento", "Operatore", "Data", "Categoria"], [row("Nota aggiunta", "Sara B.", "Oggi, 09:40", "Assistenza"), row("Piano modificato", "Marco R.", "15 febbraio", "Commerciale"), row("Anagrafica aggiornata", "Elena P.", "10 gennaio", "Cliente")], "Lo storico del cliente è vuoto."),
  subscriptions: content("Nuovo abbonamento", ["Attivi", "In rinnovo", "Sospesi"], ["Cliente", "Piano", "Scadenza", "Stato"], [row("Martina Rossi", "Annuale Platinum", "15 marzo", "In rinnovo"), row("Luca Bianchi", "Open 12 mesi", "30 novembre", "Attivo"), row("Giulia Conti", "Pilates 10", "8 ingressi residui", "Attivo")], "Nessun abbonamento corrisponde ai filtri."),
  "subscription-renewal": content("Prepara rinnovo", ["Valore proposta", "Giorni residui", "Vantaggi"], ["Opzione", "Durata", "Importo demo", "Valutazione"], [row("Rinnovo attuale", "12 mesi", "€ 1.200", "Consigliato"), row("Open semestrale", "6 mesi", "€ 720", "Alternativa"), row("Pilates Plus", "10 ingressi", "€ 300", "Aggiuntivo")], "Nessuna proposta di rinnovo disponibile."),
  plans: content("Nuovo piano", ["Piani attivi", "Più scelto", "Da revisionare"], ["Piano", "Durata", "Prezzo demo", "Disponibilità"], [row("Annuale Platinum", "12 mesi", "€ 1.200", "Pubblicato"), row("Open semestrale", "6 mesi", "€ 720", "Pubblicato"), row("Pilates 10", "10 ingressi", "€ 300", "Bozza")], "Il listino non contiene piani."),
  "renewal-deadlines": content("Pianifica contatto", ["Entro 7 giorni", "Entro 30 giorni", "Contattati"], ["Cliente", "Piano", "Scadenza", "Contatto"], [row("Martina Rossi", "Annuale Platinum", "15 marzo", "Da pianificare"), row("Luca Bianchi", "Open 12 mesi", "22 marzo", "Confermato"), row("Giulia Conti", "Pilates 10", "30 marzo", "Da contattare")], "Nessun rinnovo in scadenza nel periodo."),
  "membership-fee": content("Registra quota", ["Quote regolari", "Da rinnovare", "Importo demo"], ["Cliente", "Anno", "Importo", "Stato"], [row("Martina Rossi", "2026", "€ 25", "Da versare"), row("Luca Bianchi", "2026", "€ 25", "Regolare"), row("Giulia Conti", "2026", "€ 25", "Regolare")], "Nessuna quota associativa da mostrare."),
  payments: content("Registra pagamento", ["Incassato oggi", "Residui", "Rate scadute"], ["Cliente", "Causale", "Importo", "Stato"], [row("Martina Rossi", "Secondo acconto", "€ 250", "Parziale"), row("Luca Bianchi", "Rinnovo annuale", "€ 1.200", "Incassato"), row("Giulia Conti", "Quota associativa", "€ 25", "Incassato")], "Nessun pagamento nel periodo selezionato."),
  "annual-installments": content("Registra pagamento", ["Importo totale", "Importo pagato", "Residuo"], ["Rata", "Scadenza", "Importo", "Stato"], [row("Primo acconto", "15 gennaio", "€ 400", "Pagata"), row("Secondo acconto", "15 febbraio", "€ 250 di € 400", "Parziale"), row("Saldo", "15 marzo", "€ 400", "Scaduta")], "Nessuna rata prevista dal piano annuale."),
  "installment-deadlines": content("Registra sollecito", ["In scadenza", "Scadute", "Residuo totale"], ["Cliente", "Rata", "Scadenza", "Stato"], [row("Martina Rossi", "Saldo · € 400", "15 marzo", "Scaduta"), row("Luca Bianchi", "Seconda rata · € 300", "22 marzo", "In scadenza"), row("Giulia Conti", "Saldo · € 180", "30 marzo", "Pianificata")], "Nessuna rata in scadenza nel periodo."),
  receipts: content("Crea riepilogo", ["Ricevute emesse", "Totale demo", "Da associare"], ["Ricevuta", "Cliente", "Importo", "Stato"], [row("RIC-D-0021", "Martina Rossi", "€ 250", "Associata"), row("RIC-D-0020", "Luca Bianchi", "€ 1.200", "Associata"), row("RIC-D-0019", "Giulia Conti", "€ 25", "Da verificare")], "Nessuna ricevuta disponibile."),
  accounting: content("Nuovo movimento", ["Entrate demo", "Uscite demo", "Saldo demo"], ["Movimento", "Conto", "Importo", "Quadratura"], [row("INC-D-1042", "Cassa reception", "+ € 250", "Da verificare"), row("COS-D-0211", "Servizi", "− € 90", "Quadrato"), row("INC-D-1041", "POS", "+ € 1.200", "Quadrato")], "Nessun movimento contabile nel periodo."),
  "movement-detail": content("Aggiungi annotazione", ["Importo", "Documenti", "Controlli"], ["Evento", "Riferimento", "Data", "Esito"], [row("Registrazione", "INC-D-1042", "Oggi, 09:40", "Completata"), row("Associazione", "RIC-D-0021", "Oggi, 09:42", "Completata"), row("Quadratura", "Cassa reception", "Oggi, 18:30", "Pianificata")], "Il movimento non contiene eventi."),
  "access-control": content("Verifica accesso", ["Accessi consentiti", "Da verificare", "Non idonei"], ["Cliente", "Credenziale", "Motivo", "Esito"], [row("Martina Rossi", "Badge demo 0042", "Rata scaduta", "Da verificare"), row("Luca Bianchi", "Badge demo 0031", "Requisiti validi", "Consentito"), row("Giulia Conti", "Mobile Pass demo", "Certificato in scadenza", "In attenzione")], "Nessuna verifica accesso recente."),
  "access-log": content("Esporta registro", ["Ingressi oggi", "Uscite", "Anomalie"], ["Persona", "Varco", "Orario", "Esito"], [row("Martina Rossi", "Ingresso principale", "09:40", "Da verificare"), row("Luca Bianchi", "Ingresso principale", "09:32", "Consentito"), row("Giulia Conti", "Sala corsi", "08:55", "Consentito")], "Il registro ingressi è vuoto."),
  credentials: content("Associa credenziale", ["Attive", "In scadenza", "Sospese"], ["Credenziale", "Assegnatario", "Tipo", "Stato"], [row("CRED-DEMO-42", "Martina Rossi", "Badge", "Attiva"), row("CRED-DEMO-31", "Luca Bianchi", "Badge", "Attiva"), row("CRED-DEMO-18", "Giulia Conti", "Mobile", "Da verificare")], "Nessuna credenziale assegnata."),
  badges: content("Associa badge", ["Badge attivi", "Disponibili", "Da sostituire"], ["Badge", "Cliente", "Assegnazione", "Stato"], [row("BADGE-DEMO-42", "Martina Rossi", "10 gennaio", "Attivo"), row("BADGE-DEMO-31", "Luca Bianchi", "3 febbraio", "Attivo"), row("BADGE-DEMO-18", "Non assegnato", "—", "Disponibile")], "Nessun badge presente nel dataset demo."),
  "mobile-pass": content("Prepara istruzioni", ["Pass attivi", "Da attivare", "Revocati"], ["Profilo demo", "Dispositivo", "Ultimo utilizzo", "Stato"], [row("Martina Rossi", "Telefono demo", "Oggi, 09:40", "Attivo"), row("Luca Bianchi", "Telefono demo", "Ieri, 18:12", "Attivo"), row("Giulia Conti", "Non associato", "—", "Da attivare")], "Nessun Mobile Pass amministrativo da mostrare."),
  courses: content("Nuovo corso", ["Corsi attivi", "Sessioni oggi", "Posti liberi"], ["Corso", "Istruttore", "Prossima sessione", "Capienza"], [row("Functional Training", "Andrea M.", "Oggi, 18:00", "10 di 14"), row("Mobility", "Sara V.", "Domani, 09:00", "8 di 12"), row("Core", "Luca P.", "Domani, 19:00", "Completo")], "Nessun corso in calendario."),
  "course-detail": content("Pianifica sessione", ["Iscritti", "Posti liberi", "Presenze medie"], ["Sessione", "Istruttore", "Data", "Prenotazioni"], [row("Functional 18:00", "Andrea M.", "Oggi", "10 di 14"), row("Functional 18:00", "Andrea M.", "Venerdì", "8 di 14"), row("Functional 10:00", "Sara V.", "Sabato", "6 di 14")], "Il corso non ha sessioni pianificate."),
  workouts: content("Nuovo allenamento", ["Sessioni oggi", "Programmi attivi", "Da revisionare"], ["Allenamento", "Atleta", "Coach", "Stato"], [row("Forza A", "Martina Rossi", "Andrea M.", "Pianificato"), row("Mobilità B", "Luca Bianchi", "Sara V.", "Completato"), row("Ripresa C", "Giulia Conti", "Andrea M.", "Da revisionare")], "Nessun allenamento pianificato."),
  athletes: content("Assegna programma", ["Atleti seguiti", "Check-in oggi", "Revisioni"], ["Atleta", "Programma", "Ultimo check-in", "Stato"], [row("Martina Rossi", "Forza A", "Oggi", "Attivo"), row("Luca Bianchi", "Mobilità B", "Ieri", "Attivo"), row("Giulia Conti", "Ripresa C", "7 giorni fa", "Da contattare")], "Nessun atleta corrisponde ai filtri."),
  "pilates-bookings": content("Nuova prenotazione", ["Lezioni oggi", "Prenotati", "Lista attesa"], ["Lezione", "Orario", "Disponibilità", "Stato"], [row("Reformer Base", "09:00", "6 di 8", "Aperta"), row("Reformer Flow", "13:00", "8 di 8", "Lista attesa"), row("Reformer Plus", "18:30", "7 di 8", "Ultimo posto")], "Nessuna prenotazione nel periodo."),
  reports: content("Genera report", ["Report disponibili", "Preferiti", "Aggiornati oggi"], ["Report", "Ambito", "Periodo", "Disponibilità"], [row("Andamento club", "Direzione", "Mensile", "Disponibile"), row("Rinnovi", "Commerciale", "Trimestrale", "Disponibile"), row("Incassi", "Amministrazione", "Mensile", "Da aggiornare")], "Nessun report disponibile per i filtri."),
  "kpi-trends": content("Confronta periodo", ["Clienti attivi", "Tasso rinnovo", "Ricavo medio demo"], ["Indicatore", "Valore", "Variazione", "Andamento"], [row("Clienti attivi", "1.284", "+ 4,2%", "Positivo"), row("Tasso rinnovo", "78%", "+ 2,1 pt", "Positivo"), row("Ricavo medio", "€ 72", "− 1,3%", "In attenzione")], "Nessun KPI disponibile nel periodo."),
  "renewal-analysis": content("Esporta analisi", ["Tasso rinnovo", "Valore protetto", "Non rinnovati"], ["Segmento", "Tasso", "Valore demo", "Tendenza"], [row("Annuali", "82%", "€ 48.000", "In crescita"), row("Semestrali", "74%", "€ 21.600", "Stabile"), row("Ingressi", "61%", "€ 8.900", "In attenzione")], "Dati rinnovi non disponibili nel periodo."),
  "revenue-analysis": content("Esporta analisi", ["Incassi demo", "Ticket medio", "Residui"], ["Canale", "Incasso demo", "Incidenza", "Andamento"], [row("POS", "€ 42.800", "68%", "In crescita"), row("Bonifico", "€ 14.200", "23%", "Stabile"), row("Contanti", "€ 5.600", "9%", "In calo")], "Dati incassi non disponibili nel periodo."),
  staff: content("Nuovo operatore", ["Operatori attivi", "In turno", "Profili da verificare"], ["Operatore", "Ruolo", "Ultimo accesso", "Stato"], [row("Sara Bianchi", "Reception", "Oggi, 08:00", "Attivo"), row("Marco Riva", "Direzione", "Ieri, 18:12", "Attivo"), row("Elena Pini", "Amministrazione", "3 giorni fa", "Da verificare")], "Nessun operatore corrisponde ai filtri."),
  "operator-profile": content("Salva preferenze", ["Ruolo", "Sede", "Ultimo accesso"], ["Preferenza", "Valore", "Ambito", "Stato"], [row("Pagina iniziale", "Reception", "Interfaccia", "Impostata"), row("Notifiche", "Priorità alte", "Comunicazioni", "Attiva"), row("Densità", "Compatta", "Interfaccia", "Impostata")], "Il profilo non contiene preferenze."),
  configuration: content("Salva configurazione", ["Aree configurate", "Modifiche in bozza", "Avvisi"], ["Area", "Parametri", "Ultima revisione", "Stato"], [row("Commerciale", "12 parametri", "10 agosto", "Configurata"), row("Reception", "8 parametri", "8 agosto", "Configurata"), row("Servizi", "15 parametri", "1 agosto", "Da revisionare")], "Nessuna area configurabile disponibile."),
  "system-status": content("Aggiorna stato", ["Moduli disponibili", "Avvisi", "Ultimo controllo"], ["Modulo", "Ambito", "Controllo demo", "Stato"], [row("Anagrafiche", "Clienti", "Oggi, 09:40", "Disponibile"), row("Pagamenti", "Amministrazione", "Oggi, 09:40", "Disponibile"), row("Notifiche", "Operatività", "Oggi, 09:39", "In attenzione")], "Nessuna informazione di stato disponibile."),
  settings: content("Salva impostazioni", ["Preferenze attive", "Modifiche non salvate", "Sezioni"], ["Impostazione", "Valore", "Sezione", "Stato"], [row("Lingua", "Italiano", "Interfaccia", "Attiva"), row("Fuso orario", "Europa/Roma", "Calendario", "Attiva"), row("Formato ricevuta", "Compatto", "Amministrazione", "Modificata")], "Nessuna impostazione disponibile."),
}
